openapi: 3.0.0
info:
  title: test1
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /hello:
    get:
      summary: hello summary
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
              examples: {}
      operationId: get-hello
      description: this is hello
  /world:
    get:
      summary: world summary
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      operationId: get-world
      description: this is wolrd
  /test:
    get:
      summary: test summary
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    default: 0
                    description: 错误代码
                    enum:
                      - 0
                    $ref: ''
                  msg:
                    type: string
                  data:
                    $ref: '#/components/schemas/User'
              examples:
                example-1:
                  value:
                    code: 503
                    msg: ut officia adipisicing minim
      operationId: get-test
      description: this is test
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        status:
          type: integer
        created_at:
          type: string
      description: 用户
      x-examples:
        example-1: {}
    ApiResponse:
      title: ApiResponse
      type: object
      x-examples:
        example-1: {}
      properties:
        code:
          type: integer
          enum:
            - 0
          minimum: 0
          maximum: 999
        msg:
          type: string
        data:
          $ref: ''
    UserResponse:
      $ref: '#/components/schemas/ApiResponse'
